[package]
name = "liquid"
version = "0.13.7"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://cobalt-org.github.io/liquid-rust/"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"

build = "build.rs"

[badges]
travis-ci = { repository = "cobalt-org/liquid-rust" }
appveyor  = { repository = "cobalt-org/liquid-rust" }

[[bin]]
name = "liquid-dbg"
required-features = ["cli", "serde"]
test = false
doctest = false
bench = false
doc = false

[features]
default = ["extra-filters", "serde"]
cli = ["clap", "error-chain", "serde_yaml"]
extra-filters = []
dev = []

[dependencies]
regex = "0.2"
lazy_static = "1.0"
chrono = "0.4"
unicode-segmentation = "1.2"
itertools = "0.7.0"
url = "1.5"

serde = { version = "1.0", optional = true, features = ["derive"] }
clap = { version = "2.26", optional = true }
error-chain = { version = "0.11.0", optional = true }
serde_yaml = { version = "0.7", optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
skeptic = "0.13.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
difference = "1.0"
skeptic = "0.13.2"
serde_yaml = "0.8"
tera = "0.11"
handlebars = "1.1"
serde_derive = "1.0"
serde_json = "1.0"
